### PR TITLE
c# & UWP version of code.

### PR DESCRIPTION
**Pull request by MerrickZ**
I think it's time to make this pull request.
for those windows users, I'm re-written this tool with C# / UWP.

### CODE REVIEW

**Comment by kevin-hanselman** [comment]
Thanks for making others and myself aware of your fork, but I have no intention of supporting languages/apps beyond the current Bash script. Furthermore, with the latest news, I plan on permanently moving this repository to GitLab. More on that in the coming days.

**Comment by MerrickZ** [comment]
oh
well
bye

**Comment by kevin-hanselman** [comment]
@anphorea FYI: After a less-than pleasant experience trying to import a dozen or so repositories into GitLab, I've decided to suspend migration for the time being.

**Comment by MerrickZ** [comment]
yeah M$ is not a fool who don't know which one is better.
Gitlab is tooooooo slow for me to access.

**Pull request closed without merging**
